apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: student-project 
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol:   TCP
      port:       3000
      targetPort: 3000
      nodePort:   31080
