---
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: frontend-deployment
  namespace: student-project 
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend  
    spec: 
      containers: 
      - name: frontend-instance 
        image: docker.io/raedsebti/frontend-instance:v0.1 
        env: 
        - name: API 
          value: http://nodejs-service:4000/get-students 
...

