---
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: nodejs-deployment
  namespace: student-project 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels: 
        app: nodejs  
    spec: 
      containers: 
      - name: nodejs-instance 
        image: raedsebti/nodejs-instance:latest 
        envFrom:
        - configMapRef:
            name: mysql-configmap
        - secretRef:
            name: mysql-secret
...
